adjective1 = input("Enter an adjective(description): ")
noun1 = input("Enter an noun(place, person, thing): ")
adjective2 = input("Enter an adjective(description): ")
verb1 = input("Enter a verb enging with 'ing': ")
adjective3 = input("Enter an adjective(description): ")

print(f"Today I went to a {adjective1} zoo.")
print(f"In an exhibit, I saw a {noun1}")
print(f"{noun1} was {adjective2} and {verb1}")
print(f"I was {adjective3}!")
